FROM openjdk:8-jdk-alpine
MAINTAINER Senthilkumar
RUN apk --no-cache add netcat-openbsd

COPY ./configserverclientdocker.jar /opt/spring-cloud/lib/

COPY ./config-client-entrypoint.sh /opt/spring-cloud/bin/

RUN chmod +x /opt/spring-cloud/bin/config-client-entrypoint.sh
